# ----- Spring 框架配置 -----
logging.level.root=INFO

# ----- 数据库配置 -----
spring.jpa.hibernate.ddl-auto=update

# ----- 数据库账户配置 -----
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
