# ----- Spring 框架配置 -----
spring.application.name=TeaNeko-Paper
app.version=${teaneko.plugin.version:unknown}
server.port=${teaneko.web.port:6692}

# ----- 数据库通用配置 -----
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.threads.virtual.enabled=true

# ----- 定时器配置 -----
tea-neko.timer.update-delay-ms=10
tea-neko.cache.general-clean-rate-ms=1000

# ----- 其他配置 -----
tea-neko.database.max-retry-count=8
