# ----- Spring 框架配置 -----
spring.application.name=TeaNeko-Paper
app.version=${teaneko.plugin.version:unknown}
server.port=${teaneko.web.port:6691}

# ----- 数据库配置 -----
spring.datasource.url=jdbc:h2:file:${teaneko.paper.data-directory}/database/teaneko;MODE=MySQL;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.threads.virtual.enabled=true

# ----- 定时器配置 -----
tea-neko.timer.update-delay-ms=10
tea-neko.cache.general-clean-rate-ms=1000

# ----- 机器人配置 -----
tea-neko.bot.default-name=TeaNeko

# ----- 其他配置 -----
tea-neko.database.max-retry-count=8
